### ISSUE TITLE
Stake amount goes negative

### ISSUE THREAD

**Issue by SeanMcOwen** [BlockScience/aztec-gddt#167]
<img width="1122" alt="image" src="https://github.com/BlockScience/aztec-gddt/assets/28468980/816ca82f-ad73-4713-aaac-554089ef9515">

**Comment by danlessa** [comment]
I've added a test for capturing this behavior (PR #169). As of now, the `main` branch indeed has this behavior

**Comment by danlessa** [comment]
From what I investigated, this is being caused by sequencers being slashed when they don't have enough staked amount to cover the slash during the CommitBond phase.

Possible solutions:
1) Disallow sequencers that don't have enough staked amount to propose or get their proposals accepted
2) Set the slash value to zero
3) Assume that the sequencers will deposit some tokens when slashed.

Solution 2) is the simplest one.

**Comment by jackhack00** [comment]
@danlessa 
lets do 1.
initial stake = 32 (ETH)
min stake = 30 (ETH) 

proposals only coming from sequencers with stake > min stake
when sequencers get slashed (but havent earned) they have essentially two slashes (at 1 eth slash) before dropping 
for testing (with 3 agents) this might get wonky though

**Comment by danlessa** [comment]
ok, will implement it asap

**Comment by danlessa** [comment]
Solved by #170
