### ISSUE TITLE
Would censored blocks impact proposals being added or whether those proposals get picked up?

### ISSUE THREAD

**Issue by SeanMcOwen** [BlockScience/aztec-gddt#284]
Right now the series is taken into account for s_transactions_new_proposals and if it is censored no new proposal comes out of it

But wouldn't it actually be more about a proposal being selected or not, not whether a proposal can be created?

There is small nuances here in that censoring might end midway through and also isn't censoring really more so about the specific lead rather than the time?

**Comment by jackhack00** [comment]
Don't fully understand "There is small nuances here in that censoring might end midway through and also isn't censoring really more so about the specific lead rather than the time?"

However: A proposal being created is bundling two things for simplification - 1. The sequencer locally computes their score and builds a block 2. The sequencer globally publishes their proposal on L1. 
Since a local proposal is pretty worthless, inclusion on L1 is necessary for anyone to know about it. Ergo, proposals can be censored

**Comment by SeanMcOwen** [comment]
Point for this one was with censorship eventually it might get picked up?

**Comment by SeanMcOwen** [comment]
But with Aztec there is discrete phases that end

**Comment by SeanMcOwen** [comment]
So censorship actually becomes an issue that isn't just kicking the can down the road
