### ISSUE TITLE
Prover Slashing is Implemented

### ISSUE THREAD

**Issue by danlessa** [BlockScience/aztec-gddt#79]
This is a continuation of issue #46 

> Slashing the Prover if: No Rollup Proof finalized, even though 1) + 2) + 3) The Prover slashing goes towards the commitment bond

**Comment by jackhack00** [comment]
Merging Issues as I created duplicate: 
Currently, we slash the sequencer when either no commitment bond is put down, or when content is not revealed.
However, when both are true, there is still the possibility that no rollup proof is submitted.
In that case, commitment bond should be slashed.

Currently, the commitment bond is put down without a source (we just assign an amount).

Changes needed:

When assigning commitment bond, do a transfer from Prover UUID balance.
If a rollup proof is successfully finalized, return the commitment bond to the Prover UUID balance.
If a rollup proof is not successfully finalized, slash part of the commitment bond (through new slash param), return the rest.

**Comment by jackhack00** [comment]
Decision: 
We slash from Prover directly, since transferring back and forth each time (when in happy path) seems to make zero difference conceptually.
So: 
Similar to Sequencer Slashing, we slash the Prover directly when no rollup proof is submitted.
Needs param for commitbond (amount), currently situated in logic.py for commit bond.
Slashes entire commitbond (so uses same param for slashing).

**Comment by jackhack00** [comment]
Closed with #98
